[ruff]
line-length = 88
exclude = ["tests/*", "docs/*", "scripts/*"]
extend-ignore = ["E501", "E203"]
per-file-ignores = {
    "__init__.py": ["F401"],
}
target-version = "py310"
fixable = true
select = ["F", "E", "W", "C", "B"]