name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - run: uv python install
      - run: uv sync --locked --all-extras
      - run: uvx nox -s lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - run: uv python install
      - run: uv sync --locked --all-extras
      - run: uvx nox -s format

  type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - run: uv python install
      - run: uv sync --locked --all-extras
      - run: uvx nox -s type_check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - run: uv python install
      - run: uv sync --locked --all-extras
      - run: uvx nox -s test

  test_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - run: uv python install
      - run: uv sync --locked --all-extras
      - run: uvx nox -s test_integration

  test_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - run: uv python install
      - run: uv sync --locked --all-extras
      - run: uvx nox -s test_all

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - run: uv python install
      - run: uv sync --locked --all-extras
      - run: uvx nox -s docs

  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - run: uv python install
      - run: uv sync --locked --all-extras
      - run: uvx nox -s safety
